groups:
  - name: traefik-alerts
    rules:
      # Traefik high request rate
      - alert: TraefikHighRequestRate
        expr: rate(traefik_service_requests_total[1m]) > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High Traefik request rate detected"
          description: "More than 50 req/sec in the last minute."

      # Traefik 5xx errors
      - alert: TraefikHigh5xxRate
        expr: rate(traefik_service_requests_total{code=~"5.."}[1m]) > 5
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "High 5xx error rate in Traefik"
          description: "More than 5 5xx errors/sec in the last minute."

      # Certificate expiration
      - alert: SSLCertExpiringSoon
        expr: traefik_tls_cert_expiry_days < 10
        for: 1h
        labels:
          severity: warning
        annotations:
          summary: "SSL certificate is expiring soon"
          description: "Certificate will expire in less than 10 days."

      # Traefik dashboard unavailable
      - alert: TraefikDashboardDown
        expr: up{job="traefik"} == 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Traefik dashboard is down"
          description: "Prometheus cannot reach the Traefik metrics endpoint."