global:
  scrape_interval: 15s
  
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

scrape_configs:
  - job_name: 'traefik'
    static_configs:
      - targets: ['reverse-proxy:8082']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

rule_files:
  - "alert.rules.yaml"